[ignore]

glob = [
    # Ignore files and directories matching these glob patterns.
    # See https://docs.python.org/3/library/glob.html
    'vendor/**',
    # Monorepo
    'logs/**',
    'venv/**',
    'input/**',
    'output/**',
    # ems-frontend
    'node_modules/**',
    'dist/**',
    'build/**',
    'package-lock.json',
    'src/gql/**',
]
regex = [
    # Ignore files and directories matching these regex patterns.
    # See https://learnbyexample.github.io/python-regex-cheatsheet/
]
